//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobilePhone
    {
        public int MobileID { get; set; }
        public string MobileName { get; set; }
        public string MobileOS { get; set; }
        public string Picture { get; set; }
        public string Video { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> SaleOff { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Screen { get; set; }
        public string Camera { get; set; }
        public Nullable<int> RAM { get; set; }
        public string Resolution { get; set; }
        public string CPU { get; set; }
        public string MainCamera { get; set; }
        public Nullable<int> Size { get; set; }
        public string PictureGreen { get; set; }
        public string PictureOrange { get; set; }
        public string PictureBlack { get; set; }
        public string PictureRed { get; set; }
        public string PictureBlue { get; set; }
        public Nullable<int> CustomerBought { get; set; }
        public string TimeInsurance { get; set; }
        public Nullable<int> CustomerLike { get; set; }
        public Nullable<bool> NewMobile { get; set; }
    }
}
